sudo: false
language: ruby
rvm:
  - 2.3.4
  - 2.4.3
  - 2.5.1
env:
  - CI=true
before_install: gem install bundler -v 1.15.2
matrix:
  include:
    - gemfile: graphql-1.7.gemfile
      env: GRAPHQL_RUBY_VERSION=1_7
    - gemfile: graphql-1.8.gemfile
      env: GRAPHQL_RUBY_VERSION=1_8
